#Keep Secret
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealedsecret
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{cluster-manager repo}}
    targetRevision: HEAD
    path: sealedsecret
  destination:
    server:   https://kubernetes.default.svc
    namespace: {{$app-namespace}}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
  - group: bitnami.com
    kind: SealedSecret
    jsonPointers:
    - /metadata/creationTimestamp
---
#App service
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{$app-name}}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{cluster-manager repo}}
    targetRevision: HEAD
    path: {{$inner-path}}
  destination:
    server:   https://kubernetes.default.svc
    namespace: {{$app-namespace}}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
  - group: bitnami.com
    kind: SealedSecret
    jsonPointers:
    - /metadata/creationTimestamp
