#i use free cert in 
apiVersion: cert-manager.io/v1
kind: Certificate letsencrypt
metadata:
  name: {{$app-name}}
spec:
  secretName: {{$cert-name}}
  renewBefore: 240h0m0s
  dnsNames:
  - {{$domain-name}}
  issuerRef:
    name: {{$app-name}}
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{$app-name}}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
spec:
  tls:
  - hosts:
    - {{$domain-name}}
    secretName: {{$cert-name}}
  rules:
  - host: {{$domain-name}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{$app-name}}
            port:
              number: {{$port}}